org.gradle.jvmargs=-Xmx4G
meta_modid=redstonepen
meta_issues=https://github.com/stfwi/redstonepen/issues
meta_download=https://github.com/stfwi/redstonepen/
# check these on https://fabricmc.net/develop
loom_version=1.14-SNAPSHOT
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.5
loader_version=0.19.2
fabric_version=0.141.4+1.21.11
mod_version = 1.12.43
